#!/bin/bash

# Set URL
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

# Make API request
curl -s -f "$URL" -o data.json

# Check for errors
if [ $? -ne 0 ]; then
  echo "[$(date)] Failed to fetch Pikachu data from API: $URL" >> errors.txt
fi
